### PR TITLE
update feature count to new version

### PR DESCRIPTION
**Pull request by bgruening**
Hi @yhoogstrate,

we had some complaints about the complicated sorting options. So we decided to update the version as it seems that featureCounts now sorts by them self if needed. I also cleaned a few things up.

Hope this is ok for you.
Cheers,
Bjoern

### CODE REVIEW

**Comment by yhoogstrate** [comment]
@bgruening Great to see the changes,

I see that the package_...p5 is not updated, I will do that a.s.a.p. and start testing.

The files produced by featureCounts have a column header. If I remember correctly, the last time I tested this, the DESeq2 wrapper didn't allow that. When I push the latest version of featureCounts to the toolsheds, we should start thinking what the best way is to align it with the DESeq2 wrapper.

Thanks again,

Youri

**Comment by bgruening** [comment]
Sorry, had forgotten to add the package. If you are fine with the changes can you please update the TS?

**Comment by yhoogstrate** [comment]
I did that already! :)

**Comment by bgruening** [comment]
You are great! Thanks!

**Pull request merged**
